### ISSUE TITLE
支持一下新版的Gitlab ？

### ISSUE THREAD

**Issue by paranoidjk** [FrankFan/gitlab-tree#1]
- 新版的Gitlab 8.x.x进行了UI改版，see [here](https://gitlab.com/)
- 一些css class名字变了，举个例子

``` diff
-        initContainerML = $('.container').css('margin-left').replace('px','');
+        initContainerML = $('.ui_charcoal').css('margin-left').replace('px','');
```

**Comment by FrankFan** [comment]
是的，新版Gitlab的UI确实改版了。
如果你使用的是新版Gitlab，如果你有时间也愿意参与进来的话，请给我发个pull request吧。

2015-12-04 17:11 GMT+08:00 paranoidjk notifications@github.com:

**Comment by FrankFan** [comment]
抱歉最近没时间做兼容新版gitlab的工作
