### ISSUE TITLE
my chrome gitlab doesn't show arrow

### ISSUE THREAD

**Issue by yevgnenll** [FrankFan/gitlab-tree#10]
i have same problem #9

**Comment by FrankFan** [comment]
OK,  let me  fix this problem.

**Comment by FrankFan** [comment]
@yevgnenll  hi, I release a new version please check it.

**Comment by lijiankun24** [comment]
My Chrome gitlab doesn't show arrow, too…

**Comment by FrankFan** [comment]
@lijiankun24  
1. in code file page, refresh the page.
2. please try to upgrade a new version .

**Comment by abonec** [comment]
I don't see the arrow with the latest version too.

**Comment by FrankFan** [comment]
![image](https://cloud.githubusercontent.com/assets/1589433/22100447/a0fe2820-de6a-11e6-8f49-56f50b820e53.png)
@abonec   Did you follow the tips ?

**Comment by ekans** [comment]
I follow your tips and it doesn't work for me too.
No arrow is present.
I use Chrome 55.0.2883.87 on Ubuntu 16.04.

**Comment by FrankFan** [comment]
@ekans   Your gitlab version ?

**Comment by ekans** [comment]
I'm using using gitlab.com. So currently it's 8.16.0-rc6-ee.
Does it work with the online version?

**Comment by tastyminerals** [comment]
Does not work on chromebook for private gitlab project :(

**Comment by abonec** [comment]
@FrankFan I did all you wrote but still has now arrow. I use gitlab 8.15.3

**Comment by captainju** [comment]
no arrow for me too, using gitlab private 8.16.4 f32ee82

**Comment by damageboy** [comment]
Same here, 8.16.4 ce nothing showing up, hotkey does nothing

**Comment by archonwang** [comment]
Same error，，，
chrome 56.

**Comment by FrankFan** [comment]
if you're using www.gitlab.com , this gitlab-tree extension dosen't work now. 
because I cannot get `private_token` in www.gitlab.com.

but, with our company own gitlab service, it's OK.

![image](https://cloud.githubusercontent.com/assets/1589433/22816207/91b4c9c2-ef9b-11e6-9575-574d3f878349.png)

**Comment by FrankFan** [comment]
for www.gitlab.com,  you can use `Octotree` instead.

**Comment by archonwang** [comment]
@FrankFan 
I used the chrome plugin with my local gitlab, but I can not find the arrow. anything I have missed?

**Comment by archonwang** [comment]
I used gitlab 8.15.4, and there's no arrow shown.

**Comment by FrankFan** [comment]
@archonwang  
Firstly you need open a file url in Gitlab, then refresh the page, maybe help.
You'd better paste some screenshots here.

**Comment by archonwang** [comment]
@FrankFan 
I tried again and still found no arrow, please help checking it. Thanks.
![image](https://cloud.githubusercontent.com/assets/834512/23117214/96aa7c06-f789-11e6-8879-dd6273dce7bc.png)

my environment is
![image](https://cloud.githubusercontent.com/assets/834512/23117242/bc3b7e7a-f789-11e6-8c78-b9867b9b67f4.png)

**Comment by FrankFan** [comment]
@archonwang 
http://gitlab.xxx.com/your_group/your_project/blob/master/package.json
please try after this url loaded

**Comment by archonwang** [comment]
@FrankFan 

I tried http://[gitlabste]/[username]/[projectname]/blob/master/package.json, and it occur 404.

where the package.json file from. any configuration I have missed? 

Thanks.

**Comment by FrankFan** [comment]
@archonwang   
that url just an example, I mean you first need load a code file url.

**Comment by archonwang** [comment]
@FrankFan 
I tried the file with url like 
http://[gitlabste]/[username]/[projectname]/blob/master/filenmame
and it's display ok

there's still nothing,
Could the plugin conflict each other?

I have installed octotree,

**Comment by FrankFan** [comment]
I guess maybe there are some errors when execute javascript,  
can you check the Browser Console whether there are errors or not ?

**Comment by archonwang** [comment]
OK, I will tried to test it. Thanks. I will reply later..
