### ISSUE TITLE
Not working on Gitlab 8.17

### ISSUE THREAD

**Issue by Fridus** [FrankFan/gitlab-tree#13]
Maybe the same reason than [octotree](https://github.com/buunguyen/octotree)

**Comment by FrankFan** [comment]
hi:
now support gitlab 9.x in v1.6;
gitlab 8.x use v1.5(in history release)

**Comment by Fridus** [comment]
@FrankFan Not working with my gitlab 10.3 :(

**Comment by FrankFan** [comment]
@Fridus   Hi,  Sorry
I don't have gitlab 10.x environment so I did not test this extension at all. 

Maybe someday later will support gitlab 10.x

**Comment by Fridus** [comment]
gitlab.com is in v10 :) You can try with it ?

**Comment by FrankFan** [comment]
OK, I can do it.
waiting for my news
