### ISSUE TITLE
It doesn't work in my company's GitLab

### ISSUE THREAD

**Issue by RitterHou** [FrankFan/gitlab-tree#14]

**Comment by udoless** [comment]
Same issue

**Comment by FrankFan** [comment]
could you paste some screenshots here ?

**Comment by RitterHou** [comment]
This plugin works well in Gitlab. 
however, my company is building our git repository by [Gitlab CE](https://gitlab.com/gitlab-org/gitlab-ce), when i view our private gitlab, the tree didn't show😢.

**Comment by FrankFan** [comment]
@RitterHou  
now support gitlab 9.x
