### ISSUE TITLE
Don't send request if apiProjects or private_token are empty

### ISSUE THREAD

**Issue by yvesyao** [FrankFan/gitlab-tree#15]
![image](https://cloud.githubusercontent.com/assets/7723729/24185395/ee046fde-0f0d-11e7-89d7-fc99873662d2.png)
The image shows this plugin sends request even if apiProjects or private_token are empty, which may cause a request for the current page. This action is useless and may cause error(when current url needs additional params in header).

**Comment by FrankFan** [comment]
@yvesyao   yes， This is a question.   What's your gitlab's version ?

**Comment by yvesyao** [comment]
I don't know and it doesn't matter... The problem above happens when I access none-gitlab-websites, and this tool works well with my gitlab.

**Comment by FrankFan** [comment]
oh, I see, thank you for using this tool.
Please let me know if there are any problems.
