### ISSUE TITLE
gitlab-tree不能预览

### ISSUE THREAD

**Issue by qianlongo** [FrankFan/gitlab-tree#17]
试试打开公司里面的gitlab仓库。

但是什么反应的都没有，没有出现箭头，不能预览

**Comment by FrankFan** [comment]
真的么？
你先访问一个代码文件，再刷新看看页面左上角是否出现箭头？
如果仍然没有出现，看下控制台是否报错了？

**Comment by qianlongo** [comment]
控制台也没有报错

**Comment by edwinszhang** [comment]
公司局域网，没有反应...

**Comment by PhoenixMenia** [comment]
我的也没有出现，控制台报错了：Error in response to storage.set: TypeError: Cannot read property 'init' of undefined

**Comment by yeyulei** [comment]
![image](https://user-images.githubusercontent.com/32812519/31591529-29e6a4de-b253-11e7-9d28-9d36bf52c786.png)


没有看到有箭头，请问是如何使用的呢？

**Comment by yeyulei** [comment]
![image](https://user-images.githubusercontent.com/32812519/31591550-571623da-b253-11e7-8133-35f1521ba89d.png)


没有看到有箭头，请问是如何使用的呢？

**Comment by FrankFan** [comment]
统一回复： 现在支持 gitlab CE 9.x 版本， 请使用。
