### ISSUE TITLE
gitlab 9 以后不支持

### ISSUE THREAD

**Issue by jackcooper2015** [FrankFan/gitlab-tree#18]
gitlab 9 以后不支持

**Comment by FrankFan** [comment]
gitlab都出到9了？   你们公司用了么？

**Comment by jackcooper2015** [comment]
是的

**Comment by agvald** [comment]
I would love to see gitlab 9 support 😍

**Comment by agvald** [comment]
I looked a bit into the code and i think it is due to that it can't find the api_token
https://github.com/FrankFan/gitlab-tree/blob/43f43c0f1b738c3d561d927225264e5fdf2070d2/src/gitlabtree.js#L20-L56

**Comment by FrankFan** [comment]
@agvald   Yes, you are right, can't find the api_token in gitlab 9..
Fortunately, I found a new way to get the api_token in gitlab9, I will upgrade the code in these days.

thank you.

**Comment by FrendEr** [comment]
同求支持gitlab9.x版本

**Comment by zidoshare** [comment]
希望能尽快支持9.x版本,谢谢大神

**Comment by houko** [comment]
希望能尽快支持9.x版本,谢谢大神

**Comment by tomothumb** [comment]
Im looking forward to use gitlab 9.

**Comment by FrankFan** [comment]
@tomothumb   @xiaomoinfo   @zidoshare   @FrendEr  @jackcooper2015 

### now support gitlab 9.x please upgrade the chrome extension to use.
