### ISSUE TITLE
自己搭建的 gitlab9 社区版 不支持吗

### ISSUE THREAD

**Issue by hustlong** [FrankFan/gitlab-tree#19]
好像不支持

**Comment by FrankFan** [comment]
@hustlong  可能升级后有些API不支持吧， 我这里没有gitlab9的环境， 没法复现， 你看看控制台有没有报错？

**Comment by FrankFan** [comment]
@hustlong   Gitlab9 这个版本没试过， 现在还是不行么？

**Comment by hustlong** [comment]
上次试了不行，然后就卸载了 =====

**Comment by FrankFan** [comment]
好吧， Gitlab9 这个版本可能有问题， 我这里没法复现， issue 先关了……
