### ISSUE TITLE
有报错

### ISSUE THREAD

**Issue by loojk2008** [FrankFan/gitlab-tree#2]
Uncaught TypeError: Cannot read property 'replace' of undefined

```
       apiProjects = apiRootUrl;
        apiRepoTree = apiRootUrl + project_id + '/repository/tree';
        var apiFileContent = apiRootUrl + project_id + '/repository/files';

        initContainerML = $('.container').css('margin-left').replace('px','');

        localStorage.removeItem('loadedDirs');
    }

    // 处理右侧gitlab的宽度
```
- Uncaught TypeError: Cannot read property 'replace' of undefinedinitVariables @ gitlabtree.js:64init 
- @ gitlabtree.js:498(anonymous function) 
- @ gitlabtree.js:552jQuery.Callbacks.fire 
- @ jquery.js:1037jQuery.Callbacks.self.fireWith 
- @ jquery.js:1148jQuery.extend.ready 
- @ jquery.js:433completed @ jquery.js:103

![xxddd](https://cloud.githubusercontent.com/assets/7675430/11990397/e08fca50-aa47-11e5-8066-bbcb6229a319.jpg)

**Comment by FrankFan** [comment]
谢谢提供截图，这个问题在1.4版本已经修复了。
你更新下试试。

**Comment by mmfei** [comment]
没修复

**Comment by FrankFan** [comment]
@mmfei    多谢pull request ， 已 merge
