### ISSUE TITLE
支持自己安装的GitLab 

### ISSUE THREAD

**Issue by edwinszhang** [FrankFan/gitlab-tree#20]
Hi，Frank
没仔细看源码，想问下能适配自己局域网安装的 GitLab 吗？
想知道在哪边可以改，或者可不可以剥离出来在 settings 里面设置。

B/R
Ed.

**Comment by FrankFan** [comment]
@edwinszhang    完全支持自己局域网安装的Gitlab， 请问你那边Gitlab版本是多少？
最近有几位朋友反映这个插件不起用。。。。

**Comment by edwinszhang** [comment]
@FrankFan 9.1.4

**Comment by FrankFan** [comment]
收到， 我抽空看下这个问题。

**Comment by ouyangpeng** [comment]
@FrankFan  gitlab版本9.4.1并不支持功能，能不能完善下？？

Octotree 也在github官网写了不在支持gitlab
>GitLab is no longer supported: As of version 2.1.0, Octotree no longer supports GitLab. There are 2 reasons for this. First, GitLab has changed so much recently that it would take a lot of effort to keep Octotree up to date. Second, the GitLab team has told me they would build a tree feature in GitLab itself. I can't afford working on something knowing my effort will be irrelevant any time soon. That being said, if anyone wants to work on supporting the new GitLab, I'll gladly accept contributions to add back GitLab support.

**Comment by sinchang** [comment]
在 GitLab Community Edition 8.14.4 版本无法使用。

**Comment by FrankFan** [comment]
@edwinszhang  
现在支持 gitlab CE 9.x 版本， 请使用。

**Comment by FrankFan** [comment]
@ouyangpeng    
现在支持 gitlab CE 9.x 版本， 请使用。

**Comment by FrankFan** [comment]
@sinchang  
gitlab CE 8.x 版本， 请使用v1.5。
