### ISSUE TITLE
Chrome 请求重复提交影响测试

### ISSUE THREAD

**Issue by edwinszhang** [FrankFan/gitlab-tree#21]
Hi, Frank,

额，最近用chrome测试开发的时候遇到点问题。 使用你的 chrome 插件之后，调用其他网站会出现重复请求。情况类似：http://blog.csdn.net/millerwang23/article/details/51077247

然后排查了chrome 插件，发现你的插件会导致进去两次。 XD
以下是百度的样例。
https://snag.gy/D5WvnK.jpg

可能跟设计的机制有关吧，暂时就把插件禁掉了。希望 check 下~

B/R,
Ed

**Comment by FrankFan** [comment]
@edwinszhang  感谢反馈，我check一下~

**Comment by FrankFan** [comment]
@edwinszhang  你的截图url打不开，能否再贴一下贴到这里？

**Comment by edwinszhang** [comment]
<img width="1831" alt="default" src="https://user-images.githubusercontent.com/12592437/27523844-ad21a586-5a62-11e7-8e9c-4ad4b32ede8e.png">
<img width="1817" alt="default" src="https://user-images.githubusercontent.com/12592437/27523850-bbc8d3c0-5a62-11e7-8a86-d9b442af7141.png">

**Comment by crossoverJie** [comment]
同样的问题。

一直以为是浏览器问题，反复卸载安装多次依然这样。🤣

使用时:

![](https://ws3.sinaimg.cn/large/006tNc79ly1fko33xvokkj310k02kgm3.jpg)

去掉后:

![](https://ws4.sinaimg.cn/large/006tNc79ly1fko36vxj44j312905igmr.jpg)

**Comment by FrankFan** [comment]
最新版本v1.6已解决，issue先close了
