### ISSUE TITLE
gitlab-tree插件不能用

### ISSUE THREAD

**Issue by lixiaohao** [FrankFan/gitlab-tree#22]
![image](https://user-images.githubusercontent.com/10045637/30151948-14e039c0-93e4-11e7-86ed-f4ed96349ae4.png)
gitlab界面如下所示：
![Uploading image.png…]()

**Comment by FrankFan** [comment]
@lixiaohao   
你的gitlab版本是多少？ 如果是9.x的话请使用最新版本插件v1.6.
如果是gitlab8.x，请使用版本v1.5.
