### ISSUE TITLE
still not work

### ISSUE THREAD

**Issue by SimplyY** [FrankFan/gitlab-tree#28]
in alibaba gitlab。

GitLab Community Edition 8.3.2

**Comment by KentonYu** [comment]
Gitlab Edition 9.4.5 not work

**Comment by catplays** [comment]
Gitlab Edition  7.13.4 not work,it's menu like this
![image](https://user-images.githubusercontent.com/14192975/37883989-536ecf96-30e0-11e8-9b7b-7ea7d53dcc90.png)

**Comment by jinhe1314** [comment]
GitLab Community Edition 9.0.5 not work

**Comment by FrankFan** [comment]
@jinhe1314   不可能吧， 9.x 的版本绝对是支持的，你定位到  [Repository -> Files] 页面， 给我截图看看

**Comment by codering** [comment]
GitLab Community Edition 8.7.5 不行

我连`Repository `这个菜单都没有，是不是版本太老了。。。

**Comment by KentonYu** [comment]
@FrankFan  V9.4.5
 ![image](https://user-images.githubusercontent.com/11837283/37889825-cfc388fa-3100-11e8-8dc5-1af94cdd1c3b.png)

**Comment by aztack** [comment]
需要使用Old Navigation才可以:
![image](https://user-images.githubusercontent.com/782871/37892082-2b3381d8-3109-11e8-8cf5-9e7a9ec03f43.png)

**Comment by FrankFan** [comment]
@KentonYu   哈哈哈， 你这个case我反应过来了， 我代码里判断是应为 xx == 'Files' ， 你用的是中文版【文件】…… 

我再想下怎么改吧。
或者你改成英文版的试试看。

**Comment by urzz** [comment]
7.13.3表示木有效果 @FrankFan

**Comment by FrankFan** [comment]
@urzz  抱歉我这边没有 7.x  的环境，无法debug。。。。

让你们IT同事升级gitlab的版本吧。。

**Comment by jerry-chao** [comment]
![image](https://user-images.githubusercontent.com/11730593/38028207-c4b06d64-32c4-11e8-9dee-5d537afe37f0.png)
![image](https://user-images.githubusercontent.com/11730593/38028314-2e241d40-32c5-11e8-9989-5307526060ed.png)

不能正常工作，上面是crhome的版本，安装的是插件是最新的版本

**Comment by FrankFan** [comment]
@jerry-chao   请问你用的gitlab 版本是多少？ 
gitlab的版本可以从类似 gitlab.your_site.com/help 页面获取。

**Comment by jinhe1314** [comment]
我也是中文版的
貌似没有办法切换回英文了

**Comment by FrankFan** [comment]
@jinhe1314    不好意思哈。  英文版能用吧？

**Comment by jinhe1314** [comment]
没有办法切换回英文

**Comment by RishyPa** [comment]
GitLab Community Edition 8.14.1 e45bf3d not work.

**Comment by wenjiangtao** [comment]
halo老大，我的gitlab不能用额，版本9.1.0~~~你是怎么识别的呢？识别域名？我的域名里没有gitlab字样哦~~

**Comment by FrankFan** [comment]
@wenjiangtao   不是识别域名，识别gitlab字样这种方式就不通用了。只是针对特定版本获取token而已。

**Comment by wenjiangtao** [comment]
但是表示我的gitlab不能用额……

**Comment by wenjiangtao** [comment]
work了……要进file页才可以……

**Comment by FrankFan** [comment]
@wenjiangtao   恭喜🎉， 多谢使用~

**Comment by xfields** [comment]
gitlab 8.8.4  版本不可用，域名是 git.x.y 这种格式。是要升级 gitlab 版本，还是因为域名不匹配？

**Comment by FrankFan** [comment]
@xiefei89   gitlab 8.x 版本应该也是支持的， 和域名格式没关系，程序会检测的。 你要定位到 【Repository --> Files 】 页面。

**Comment by xfields** [comment]
8.8.4 版本的目录结构是这样，并没有 Repository 这个路由。
![image](https://user-images.githubusercontent.com/6301070/39515661-60010eda-4e2d-11e8-996f-40837ac9b53c.png)

**Comment by FrankFan** [comment]
@xiefei89  现在的问题是我这里没有8.8.4的gitlab环境可以让我调试，我也很苦恼…… 要不你自己调试下代码看看

**Comment by kuankuanlv** [comment]
> Gitlab Edition 7.13.4 not work,it's menu like this
> ![image](https://user-images.githubusercontent.com/14192975/37883989-536ecf96-30e0-11e8-9b7b-7ea7d53dcc90.png)

我也是7.x，你的现在好了吗

**Comment by lin-xin** [comment]
语言切换成中文无法使用，切成英语就可以，请问这个问题有处理吗？

**Comment by FrankFan** [comment]
@lin-xin  不用意思，没处理过，最近精力有限，没时间优化了，而且最新的`gitlab`推出了`Code Editor`功能，比这个插件好用。  

你要是没升级最新的gitlab版本的话，仍然想要使用这个插件，欢迎贡献代码，`PR is welcome `
