### ISSUE TITLE
Gitlab 8.6.5 使用不了

### ISSUE THREAD

**Issue by jiehua233** [FrankFan/gitlab-tree#7]
我的Gitlab版本为8.6.5，装了gitlab-tree插件后没反应，刷新页面也不起作用

**Comment by FrankFan** [comment]
不好意思， 不支持 Gitlab 8.x 版本， 只支持 Gitlab 7.x 

![image](https://cloud.githubusercontent.com/assets/1589433/15177735/37cdbea2-17a4-11e6-9547-60fb57a7846c.png)

**Comment by jiehua233** [comment]
@FrankFan 已经改用Octotress，完美支持gitlab和github，私有gitlab也可以使用

**Comment by FrankFan** [comment]
@jiehua233   是的，一开始我也使用这个，当时还不支持 `Gitlab` 所以我自己写了一个，现在看起来他那个更好用。
