### ISSUE TITLE
Gitlab tree not opening at the my gitlab

### ISSUE THREAD

**Issue by mario-amazing** [FrankFan/gitlab-tree#9]
![image](https://cloud.githubusercontent.com/assets/9537753/20244673/008483ce-a99c-11e6-9512-38d73e85bc37.png)
No arrow for open gitlab tree

**Comment by yevgnenll** [comment]
why did you close this issue?
i have same problem if you've done
could you let me know how did you find?

**Comment by FrankFan** [comment]
Sorry guys,  this days I've been developing a new version for supporting >8.x Gitlab, and I made it.
Please waiting for me to uploading a new version to `Google Chrome App Store`.
